# meta config (for logging, output, etc.)
meta:
  log_path: ./logs
  output_path: ./output

# pde constants
pde:
  omega0: 10.0
  omega1: 10.0
  rho: 1.0
  mu: 1.0
  r0: &r0 0.1
  r1: &r1 10.0
  degrees: [ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28 ,30, 32, 34, 36 ]
  theta_singularity: 0.1

# condition (parameterization)
condition:
  ur:
    type: shift
  utheta:
    type: shift
  uphi:
    type: shift
  p:
    type: reverse


# network architecture
network:
  ur: &default-net
    module_type: sequential
    args:
      - module_type: monomialnn
        kwargs:
          degrees: [ 1, 2 ]
      - module_type: resnet
        args: [ 2, 19 ]
        kwargs:
          n_res_blocks: 1
          n_res_units: 1024
          actv: Swish1
  utheta: *default-net
  uphi: *default-net
  p: *default-net

# curriculum
curriculum:
  r0_start: 0.1
  r1_start: 10.0
  n_curricula: 10
  epochs_per_curriculum: 4000
  advance_method: log
  size_method: log
  base_size: 2048
  min_size: 512
  max_size: 2048
  train:
    n_batches: 4
    generator:
      type: spherical
      method: equally-radius-noisy
  valid:
    n_batches: 0
    generator:
      type: spherical-static
      method: equally-radius-noisy

# weight function
weighting:
  r_mom: &default-weight
    weight: 1.
    type: softstep
    args:
      a: 10.
      b: 10.
  theta_mom: *default-weight
  phi_mom: *default-weight
  div: *default-weight

'(default-monitor)': &default-monitor
  r_min: *r0
  r_max: *r1
  theta_min: 0.1
  theta_max: 3.041592653589793
  phi_min: 0.0
  phi_max: 6.283185307179586
  r_scale: log
  shape: [ 32, 16, 2 ]

# monitor
monitor:
  residual:
    <<: *default-monitor
    check_every: 1000
    fig_dir: figs/residual
  solution:
    <<: *default-monitor
    check_every: 100
    fig_dir: figs/solution

# optimizer
optimizer:
  type: Adam
  kwargs:
    lr: 0.005
    betas: [ 0.9, 0.999 ]
